export const CAKE_RESTOCKED = "CAKE_RESTOCKED";
export const ICECREAM_RESTOCKED = "ICECREAM_RESTOCKED";
export const ICECREAM_SOLD = "ICECREAM_SOLD";
export const CAKE_SOLD = "CAKE_SOLD";
export const ADDRESS_MODIFIED = "ADDRESS_MODIFIED";
export const USER_FETCH_SUCCEEDED = "USER_FETCH_SUCCEEDED";
export const USER_FETCH_FAILED = "USER_FETCH_FAILED";
export const USER_FETCH_REQUESTED = "USER_FETCH_REQUESTED";
